name: AlbumsChallenge
options:
  bundleIdPrefix: com.regisksc
  deploymentTarget:
    iOS: "17.0"
targets:
  AlbumsChallenge:
    type: application
    platform: iOS
    sources: Sources
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.regisksc.AlbumsChallenge
    info:
      path: Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
  AlbumsChallengeTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests
    dependencies:
      - target: AlbumsChallenge
    settings:
      GENERATE_INFOPLIST_FILE: YES
